{
    "config": {
        "error": {
            "cannot_connect": "Failed to connect",
            "invalid_auth": "Enable authentication in m\u00fctesync Preferences > Authentication",
            "unknown": "Unexpected error"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Host"
                }
            }
        }
    }
}