{
    "config": {
        "error": {
            "cannot_connect": "No se pudo conectar",
            "invalid_auth": "Activar la autenticaci\u00f3n en las Preferencias de m\u00fctesync > Autenticaci\u00f3n",
            "unknown": "Error inesperado"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Host"
                }
            }
        }
    }
}